

parameters = [
    {"type": "Advance Day", "value": 0, "location": "D4"},
    {"type": "Date", "value": 'Date', "location": "I1"},
    {"type": "Temperature", "value": 0, "location": "I4"},
    {"type": "Weather", "value": 'Sunny', "location": "I2"},
    {"type": "Previous Advance", "value": 25, "location": "K23"},
    {"type": "Previous Ring Built", "value": 25, "location": "K24"},
    {"type": "Previous Threaded", "value": 25, "location": "k25"},
    {"type": "Previous Tensioned", "value": 25, "location": "K26"},
    {"type": "Previous Grouted", "value": 25, "location": "K27"},
    {"type": "My Advance", "value": 25, "location": "G23"},
    {"type": "My Ring Built", "value": 25, "location": "G24"},
    {"type": "My Threaded", "value": 25, "location": "G25"},
    {"type": "My Tensioned", "value": 25, "location": "G26"},
    {"type": "My Grouted", "value": 25, "location": "G27"},
    {"type": "Start Station", "value": 25, "location": "H18"},
    {"type": "End Station", "value": 25, "location": "H20"},
    {"type": "TSG 1", "value": 25, "location": "G30"},
    {"type": "TSG 2", "value": 25, "location": "G31"},
    {"type": "EP2", "value": 25, "location": "G32"},
    {"type": "HBW", "value": 25, "location": "G33"},
    {"type": "Office Staff", "value": 25, "location": "B7"},
    {"type": "Field Staff", "value": 25, "location": "B8"},
    {"type": "Safety", "value": 25, "location": "B9"},
    {"type": "Foreman", "value": 25, "location": "E7"},
    {"type": "Operators", "value": 25, "location": "E8"},
    {"type": "Laborers", "value": 25, "location": "E9"},
    {"type": "Cr Operators", "value": 25, "location": "E10"},
    {"type": "Mechanics", "value": 25, "location": "E11"},
    {"type": "Oiler", "value": 25, "location": "E12"},
    {"type": "Gas Tester", "value": 25, "location": "E13"},
    {"type": "Surveyor", "value": 25, "location": "E14"},
    {"type": "WA Rasic", "value": 25, "location": "I7"},
    {"type": "Tensa", "value": 25, "location": "I8"},
    {"type": "TEI", "value": 25, "location": "I9"},
    {"type": "Sixense", "value": 25, "location": "I10"},
    {"type": "Landmark", "value": 25, "location": "I11"},
    {"type": "Guard", "value": 25, "location": "I12"},
    {"type": "District", "value": 25, "location": "I13"},
    {"type": "HK", "value": 25, "location": "I14"},
    {"type": "Ballard", "value": 25, "location": "I15"},
    {"type": "Description", "value": 'value', "location": "A18"},


]
